spring.datasource.url=jdbc:postgresql://localhost:5432/naturalsamada_db
spring.datasource.username=postgres
spring.datasource.password=438110.p

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect